### ISSUE TITLE
Updated PKGBUILD on AUR

### ISSUE THREAD

**Issue by nobodywasishere** [SourceLink/uml_utilities-20070815-1#1]
Hello,
The old maintainer orphaned the uml_utilities package from the AUR and I took it over to fix it. Let me know if the updated one works, and if you or someone else wants to maintain it instead that's fine with me. https://aur.archlinux.org/packages/uml_utilities/

**Comment by SourceLink** [comment]
> Hello,
> The old maintainer orphaned the uml_utilities package from the AUR and I took it over to fix it. Let me know if the updated one works, and if you or someone else wants to maintain it instead that's fine with me. https://aur.archlinux.org/packages/uml_utilities/

That's great
